### ISSUE TITLE
Cycle Detection in Linked List

### ISSUE THREAD

**Issue by ashmeet-chhabra** [aaryahjolia/dsa_competitive-coding#11]

**Comment by ashmeet-chhabra** [comment]
Hey! I was reading the contribution guidelines and couldn't understand what this meant - "mark it Done in that folder's .md file". In the readme, do I have to create a checkbox with my file name and tick it or does it mean something else?

**Comment by aaryahjolia** [comment]
Leave that part for now! Just create .md file of your code and explanation. That's it!
