### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by Shweta2024** [aaryahjolia/dsa_competitive-coding#13]
## Description

Write a program to solve a Sudoku puzzle by filling the empty cells.

A sudoku solution must satisfy all of the following rules:
- Each of the digits 1-9 must occur exactly once in each row.
- Each of the digits 1-9 must occur exactly once in each column.
- Each of the digits 1-9 must occur exactly once in each of the 9 3x3 sub-boxes of the grid.

**Comment by Shweta2024** [comment]
@aaryahjolia  Hello sir,can you please assign this issue to me

**Comment by aaryahjolia** [comment]
Hey @Shweta2024 , It's nice to see the project title and your enthusiasm to contribute to this repo.
Currently, We are not accepting any Projects based on DSA.
If we open up projects section, You'll be informed in future.
Hope you have a great day!
