### ISSUE TITLE
Merge Two Sorted Lists

### ISSUE THREAD

**Issue by surjyaneeh** [aaryahjolia/dsa_competitive-coding#15]
Problem Link: https://leetcode.com/problems/merge-two-sorted-lists/

**Comment by surjyaneeh** [comment]
@aaryahjolia may I work on this issue?

**Comment by MohammadKaif1** [comment]
can you assign this issue to me

**Comment by aaryahjolia** [comment]
Hey @surjyaneeh , This topic is already covered in Linked list section of Hackerrank's DSA solution. Try considering any other problem or you can also contribute to concept of linked list like adding node, deleting node, etc.
Have a great day!
