### ISSUE TITLE
CodeStudio by Coding Ninjas

### ISSUE THREAD

**Issue by Atharva-3000** [aaryahjolia/dsa_competitive-coding#160]
Adding resources for solutions to questions found on **CodeStudio** by **Coding Ninjas**, since they are not present yet.

There will be separate sub folders for various topics for easy navigation, each folder with a **readme consisting of question.**

Topic wise questions will have **company name** mentioned in them.

This will be as a part of **GSSOC23**.

**Comment by Atharva-3000** [comment]
This will be as a part of **GSSoC23**.

**Comment by aaryahjolia** [comment]
Hi, Please read the [Important Announcement](https://github.com/aaryahjolia/dsa_competitive-coding/issues/305).
We are currently not accepting questions.
