### ISSUE TITLE
Connect 4 game using C++

### ISSUE THREAD

**Issue by sammi-stack** [aaryahjolia/dsa_competitive-coding#164]
Hi Me as a contributor in GSSOC'23 and I want to create a game using C++

**Comment by singh-anushka** [comment]
Can you please assign this issue to me?

**Comment by sammi-stack** [comment]
> Can you please assign this issue to me?

why?

**Comment by Mani1881** [comment]
Please assign me this issue under GSSOC 23

**Comment by sammi-stack** [comment]
@aaryahjolia @blog-a1 @sahil1710 @rachitshah07 
Anyone here who can assign the project to me under the GSSOC'23
