### ISSUE TITLE
Adding a new question: Container with most water

### ISSUE THREAD

**Issue by Vidhish-Trivedi** [aaryahjolia/dsa_competitive-coding#181]
As part of the GSSoC'23 program, I would like to contribute by adding a solution for: Leetcode 11, Container with most water.

**Comment by srushtikage** [comment]
Hi I'm GSSoC'23 Contributor. I would  like to work on this issue pls assign it to me.

**Comment by Vidhish-Trivedi** [comment]
Hello @srushtikage, as per the guidelines provided by the maintainer, they are not accepting any questions. You can refer to #305 for more details.
