### ISSUE TITLE
Generate and Add all code's link [OPEN FOR ALL]

### ISSUE THREAD

**Issue by aaryahjolia** [aaryahjolia/dsa_competitive-coding#20]
In all the .md files where there is a whole code, Copy that code, Paste it in [GFG IDE](https://ide.geeksforgeeks.org/), Run and Generate URL, Add a new section in that .md file naming 'Run Code' and paste the link in that section.
Do this for all the code that are fully written.

**Comment by ashmeet-chhabra** [comment]
I'd like to work on this

**Comment by ashmeet-chhabra** [comment]
Hey, what should i do with files that don't have the main function and the structures set up (e.g. [this](https://github.com/aaryahjolia/dsa_competitive-coding/blob/main/HackerRank%20Solutions/Data%20Structures/Linked%20List/Compare%202%20Linked%20List.md))

**Comment by aaryahjolia** [comment]
> Hey, what should i do with files that don't have the main function and the structures set up (e.g. [this](https://github.com/aaryahjolia/dsa_competitive-coding/blob/main/HackerRank%20Solutions/Data%20Structures/Linked%20List/Compare%202%20Linked%20List.md))

Leave the Hackerrank section as Hackerrank provides all the functions in it's IDE!
But do it for codeforces folder.
