### ISSUE TITLE
Add questions to the linkedlist section

### ISSUE THREAD

**Issue by karthiknadar1204** [aaryahjolia/dsa_competitive-coding#208]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23,please assign it to me

**Comment by Thrillseekr** [comment]
Hey @aaryahjolia ,
I'm Darshan Jain, and I'm thrilled to be a part of this GSSOC'23. I bring along my expertise in Data Structures and Algorithms in C++. I'm passionate about open source projects and eager to contribute and collaborate with fellow enthusiasts.

Can you please assign this to me.

**Comment by anunayandkumar** [comment]
Heyy @aaryahjolia .
I would like to add basic Linked List Code for taking input, insertion and deletion in one program . After that few more Linked List Question can be added . Accordingly please assign it to me (Under GSSoC' 23).

**Comment by karthiknadar1204** [comment]
We can work on this issue together to be honest,i can add the linked list reversal,alternate reversal and many more questions and their codes,we can discuss amongst ourselves which one to be added and can add accordingly instead of hoarding the issue
Is that fine by the maintainer and other contributors

**Comment by anunayandkumar** [comment]
I am OK with this & can work together.  Since ,It's all about Collaboration : )
