### ISSUE TITLE
Add 2 Sorting code [OPEN FOR ALL]

### ISSUE THREAD

**Issue by aaryahjolia** [aaryahjolia/dsa_competitive-coding#21]
In sorting folder's Sorting.md file, There are 4 techniques remaining. Do any 2 to get a level-1 tag.

**Comment by vickyrules** [comment]
@aaryahjolia  please assign this to me

**Comment by aaryahjolia** [comment]
Hey @deepshikha2708 , You can work on it!

**Comment by vedsom** [comment]
@aaryahjolia can i work on it?
