### ISSUE TITLE
Add BFS and DFS for Graph [OPEN FOR ALL]

### ISSUE THREAD

**Issue by aaryahjolia** [aaryahjolia/dsa_competitive-coding#22]
Add DFS and BFS techniques in Graph to get a level-1.

**Comment by munish0838** [comment]
I would like to work on this issue under HCSoC

**Comment by deepshikha2708** [comment]
can you please assign me this issue?

**Comment by coderSuren** [comment]
@aaryahjolia can you assign me this issue if no one is working on it

**Comment by vedsom** [comment]
@aaryahjolia can you assign me this issue?
