### ISSUE TITLE
LeetCode Solution's

### ISSUE THREAD

**Issue by Bhavesh-Rawat** [aaryahjolia/dsa_competitive-coding#23]
I Would Like to add LeetCode Problem's Statement with link to LeetCode and it's Solution For Array Problem's So that it will be easier for everyone to access DSA easily through this Repo. 
May I ?

**Comment by aaryahjolia** [comment]
Make a new folder like hackerrank and codeforces and start your work!

**Comment by Bhavesh-Rawat** [comment]
Till tomorrow it will be done.
