### ISSUE TITLE
Add Sliding Window Questions

### ISSUE THREAD

**Issue by shruti8302** [aaryahjolia/dsa_competitive-coding#267]
Hi @aaryahjolia,

I'm excited to contribute to GSSoc'23 by providing solutions to the most important sliding window questions. With my strong background in C++ and DSA, I'm confident in delivering high-quality explanations and solutions for these problems.
I'm eager to take on this challenge and contribute my skills to the community. Assigning me this issue would be a great opportunity for me to showcase my expertise in C++ and DSA, while also helping others understand and master sliding windows-related problems.

Best regards,
Shruti Singh

**Comment by urvi-swl** [comment]
Hi @aaryahjolia , I am a GSSoC'23 contributor have have solved around 900 questions on leetcode(https://leetcode.com/code_hobby_2404/). Please assign this issue to me.

**Comment by Harsh1350** [comment]
I want to work on this please assign me this
