### ISSUE TITLE
Adding Dijkastra Algorithm in Graph

### ISSUE THREAD

**Issue by sumitkr2000** [aaryahjolia/dsa_competitive-coding#275]
Hey @aaryahjolia I want to add the Dijkstra algorithm to the graph topic. Please assign me this issue. Thank you!

**Comment by Harsh1350** [comment]
Hey @aaryahjolia  I want to add Dijkstra algorithm to this Please assign me this

**Comment by sumitkr2000** [comment]
@Harsh1350 bro i have raised this issue. You can raise another issue which is not already raised.

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by sumitkr2000** [comment]
@UditSharma9999 i am working on this issue. Please raise another issue. Thank you
