### ISSUE TITLE
Updating Readme

### ISSUE THREAD

**Issue by sumitkr2000** [aaryahjolia/dsa_competitive-coding#277]
Hey @aaryahjolia I want to update the readme to add the contributing steps in it so that the new contributors will find it easy to contribute to your repo. Please assign me this issue. Thank you!

**Comment by void-delta** [comment]
Hey @aaryahjolia I believe that I am very qualified to add the Readme files. 
I am quite expressive and have a knack of finding the apt words that are not too outlandish for the general audience but at the same time, convey the exact message that is to be conveyed. I also understand the value of good documentation. I am confident that I will be able to update Readme files to be more informative and make it useful to new users. 
Being a part of my institute's literature club also gives me the arsenal of words that might be needed for this task.
I am currently in my second semester pursuing CSE.
I request you to kindly assign me this issue.
Thank you

**Comment by sumitkr2000** [comment]
@void-delta Bro raise another issue. I am working on this one.

**Comment by void-delta** [comment]
I don't see a reason why we can't work together on this one. It's open-source, it's good if there are multiple contributers

**Comment by sumitkr2000** [comment]
@void-delta no problem if the admin assigns to both. I am happy to work together.
