### ISSUE TITLE
Add KMP Algorithm

### ISSUE THREAD

**Issue by sumitkr2000** [aaryahjolia/dsa_competitive-coding#278]
Hey @aaryahjolia I want to add KMP Algorithm to your repo. Please assign me this issue. Thank you!

**Comment by dk172923** [comment]
Hello, I am Dhinesh. Actually I have solved  KMP algorithm in my college. So sign me up for this issue

**Comment by sumitkr2000** [comment]
@dk172923 i am already solving this issue. Please raise another issue. Thank you.
