### ISSUE TITLE
Adding Boyer- moore voting algorithm

### ISSUE THREAD

**Issue by sumitkr2000** [aaryahjolia/dsa_competitive-coding#281]
Hey @aaryahjolia I want to add the Boyer voting Algorithm. Please assign me this issue. Thank you!

**Comment by AnmolChauhan123** [comment]
Please assign this issue to me

**Comment by sumitkr2000** [comment]
@AnmolChauhan123 bro please raise another issue. I will work on it. Thank you.

**Comment by AnmolChauhan123** [comment]
Alright broo... No issue
