### ISSUE TITLE
Adding Kruskal's Algorithm

### ISSUE THREAD

**Issue by sumitkr2000** [aaryahjolia/dsa_competitive-coding#286]
Hey @aaryahjolia I want to add the Kruskal's algo to your repo. Please assign me this issue. Thank you!

**Comment by Mani1881** [comment]
hi i  solved questions in gfg.I am intrested to take part in this issue.I am gssoc 23 contributor

**Comment by sumitkr2000** [comment]
@Mani1881 i have raised this issue and will work on it. Please raise another issue. Thank you.

**Comment by Mani1881** [comment]
ok
