### ISSUE TITLE
Add reverse a link list

### ISSUE THREAD

**Issue by sumitkr2000** [aaryahjolia/dsa_competitive-coding#288]
Hey @aaryahjolia I want to add the problem reverse a linked list to your repo. Please assign me this issue. Thank you!

**Comment by pjoshi999** [comment]
Good Evening @aaryahjolia, Hope you are good. I have been practicing DSA for long time and I can give brute to optimised approach for this question with comments for better understanding. Kindly assign this issue to me.
Thank you in advance!

**Comment by Ijaiswalshivam** [comment]
can you please assign me this role

**Comment by sumitkr2000** [comment]
Bro i have already raised this issue u ...i will work on it... kindly raise another issue. Thank you.

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by sumitkr2000** [comment]
@UditSharma9999 i am working on this issue. Please raise another issue of your choice. Thank you.

**Comment by srushtikage** [comment]
Hi I'm GSSoC'23 Contributor. I would  like to work on this issue pls assign it to me.

**Comment by sumitkr2000** [comment]
@srushtikage i am working on this issue. Please raise another pr if u want to contribute. Thank you.
