### ISSUE TITLE
Flatten a linked list

### ISSUE THREAD

**Issue by sumitkr2000** [aaryahjolia/dsa_competitive-coding#289]
Hey @aaryahjolia I want to add the flatten-a-link list problem. Please assign me this issue. Thank you!

**Comment by Shivam-Batham** [comment]
Hey @aaryahjolia I want to work on this under **Gssoc23 assign me.**
i have strong understanding on the linked list & also solved the questions on this topic.

**Comment by Shivam-Batham** [comment]
Hey @aaryahjolia I want to work on this under **Gssoc23 assign me.**
i have strong understanding on the linked list & also solved the questions on this topic.

**Comment by sumitkr2000** [comment]
Don't span bro @Shivam-Batham 
@aaryahjolia check this!!!!

**Comment by Shivam-Batham** [comment]
i am not spamming this is internet issue @sumitkr2000 . it happens accidently by slow internet .
