### ISSUE TITLE
Include topics on Arrays and also include more STL elements

### ISSUE THREAD

**Issue by ePSA-eJya** [aaryahjolia/dsa_competitive-coding#325]
The array folder does not contain any resources. we can update it with problems and code snippets.
We can also add more STL elements like -map, sets etc.
Assign this task to me. I shall complete the above.

**Comment by Mani1881** [comment]
Hey @ePSA-eJya  i really want to contribute this issue.please assign to me as i am new gssoc23 contributor

**Comment by ePSA-eJya** [comment]
> Hey @ePSA-eJya i really want to contribute this issue.please assign to me as i am new gssoc23 contributor

I am a contributor myself :)
