### ISSUE TITLE
Code to implement In,Pre,Post-order traversal in a single traversal(using a single function)

### ISSUE THREAD

**Issue by ePSA-eJya** [aaryahjolia/dsa_competitive-coding#328]
The traversal techniques for the 3 different traversals have already been mentioned. However we can implement all the three using  a single stack. I would want to contribute the code for this.
I am a GSSOC'23 contributor.
Please assign this task to me @aaryahjolia

**Comment by Mani1881** [comment]
hi can I  write a code on this and i am very good at trees,bst data structures.I would want to contribute the code for this.I am a GSSOC'23 contributor.

**Comment by ePSA-eJya** [comment]
@aaryahjolia please assign this to me.
