### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by SumitKanth** [aaryahjolia/dsa_competitive-coding#33]
I will complete more than 20 pattern based on loops

**Comment by aaryahjolia** [comment]
Make a new folder naming 'Loop Patterns' and add your .md files there.

**Comment by SumitKanth** [comment]
Can I make 6 .md files in which each file contain max 5 pattern for easy way to understand all pattern ?

**Comment by aaryahjolia** [comment]
> Can I make 6 .md files in which each file contain max 5 pattern for easy way to understand all pattern ?

Make single md files as you'll have to include description and thinking also along with the code.
