### ISSUE TITLE
OOPs Concept

### ISSUE THREAD

**Issue by MohammadKaif1** [aaryahjolia/dsa_competitive-coding#35]
No OOPS concept in this DSA repository.
@aaryahjolia Please assign this issue to me..

**Comment by MohammadKaif1** [comment]
No OOPS concept in this DSA repository.
@aaryahjolia Please assign this issue to me..

**Comment by MohammadKaif1** [comment]
@aaryahjolia will you be adding a tag to it ?

**Comment by aaryahjolia** [comment]
You can contribute, Tag will be added to PR.
