### ISSUE TITLE
Topological Sort

### ISSUE THREAD

**Issue by Vidip-Ghosh** [aaryahjolia/dsa_competitive-coding#356]
Hi,
I would like to add Topological Sort Algorithm.

**Comment by Aditi323** [comment]
Please assign this to me as a GSSOC contibutor.

**Comment by VC6378** [comment]
Please assign me to add Topolgical Sort Algorithm

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by ratishjain12** [comment]
Please assign me for this issue under GSSoC'23  as I would like to add the topological sort algorithm

**Comment by Vidip-Ghosh** [comment]
> Hi, I would like to add Topological Sort Algorithm.

@aaryahjolia Please assign this issue
