### ISSUE TITLE
New Problems to be added

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [aaryahjolia/dsa_competitive-coding#37]
I would like to update this repo by adding the code of updated data of Codeforces.

**Comment by aaryahjolia** [comment]
Hey, Please specify problem numbers of codeforces you wish to add!

**Comment by Pranjal360Agarwal** [comment]
Following problems I wish to add: - 
 
A. YES or YES?
B. ICPC Balloons
C. Cypher
