### ISSUE TITLE
[GSSoc'23] Morris Traversal for Inorder and Preorder Traversal of a Tree

### ISSUE THREAD

**Issue by NehaKariya0309** [aaryahjolia/dsa_competitive-coding#395]
Hey @aaryahjolia ,
I would like to add implementation and code for Morris Traversal . I would ensure to make the code readable with proper documentation along with complexity analysis.
Thanks,
Neha Kariya

**Comment by Anjali07Patel** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.
