### ISSUE TITLE
[GSSOC'23]Egg Dropping Puzzle

### ISSUE THREAD

**Issue by Vyshnavi21504** [aaryahjolia/dsa_competitive-coding#490]
Hi,I am contributor of GSSOC'23, I want to add the egg dropping puzzle problem. Please assign me this issue.
@aaryahjolia
Thank you.

**Comment by MahraibFatima** [comment]
@aaryahjolia I want to create a egg droppin puzzle in cpp . Assign this to me. I would like to work on it.
