### ISSUE TITLE
Add LeetCode Array Problems

### ISSUE THREAD

**Issue by surjyaneeh** [aaryahjolia/dsa_competitive-coding#64]
[1.](https://leetcode.com/problems/peak-index-in-a-mountain-array/)
[2.](https://leetcode.com/problems/running-sum-of-1d-array/)
[3,](https://leetcode.com/problems/squares-of-a-sorted-array/)

**Comment by aaryahjolia** [comment]
Hey, We are restricting contributors to contribute in Competitive website solutions for HSOC like hackerrank, leetcode and codeforces.
You can still contribute to other sections.

**Comment by surjyaneeh** [comment]
> Hey, We are restricting contributors to contribute in Competitive website solutions for HSOC like hackerrank, leetcode and codeforces. You can still contribute to other sections.

Okay sure.
