### ISSUE TITLE
Add LetCodes Solutions

### ISSUE THREAD

**Issue by Bhavesh-Rawat** [aaryahjolia/dsa_competitive-coding#69]
Actually this issue was assigned to me but unintentionally i closed it.

**Comment by aaryahjolia** [comment]
Leave for now, Contribute to other sections as this section is restricted now from contributing!

**Comment by Bhavesh-Rawat** [comment]
But at my end I have already done it as it was assigned to me by you , it was closed by me unintentionally so can you please merge it otherwise my efforts would be wasted.

**Comment by aaryahjolia** [comment]
Okay it'll be considered but the level will be decreased.

**Comment by Bhavesh-Rawat** [comment]
Yes it's all right
